name: deploy pages

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/pages.yaml
      - lib.typ
      - assets/**
      - content/**
      - public/**
  workflow_dispatch:

env:
  JUST_COLOR: always

jobs:
  build:
    # https://vite.dev/guide/static-deploy.html#github-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: install tools
        run: |
          nix profile add "nixpkgs#just" && just -V
          nix profile add "nixpkgs#fd" && fd -V
          nix profile add "nixpkgs/c6d65881c5624c9cae5ea6cedef24699b0c0a4c0#typst" && typst -V

      - name: build
        run: just serve_base='blog' build-all

      - uses: actions/configure-pages@v5

      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/blog
      - name: deploy
        uses: actions/deploy-pages@v4
